[tool.mypy]
python_version = "3.13"
explicit_package_bases = true
namespace_packages = true

# Игнорировать отсутствующие импорты для этих модулей
ignore_missing_imports = true

# Игнорировать конкретные модули
[[tool.mypy.overrides]]
module = [
    "typer.*",
    "pytest.*",
    "pyfakefs.*",
    "typer",
    "pytest",
    "pyfakefs"
]
ignore_missing_imports = true
